### ISSUE TITLE
stepup-middleware cache dir needs to be writable

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-devconf#7]
A quick fix is 
```docker compose exec middleware chown -R www-data /var/www/html/var/cache/prod/```
but this should be fixed in the component or during the creating of the image

**Comment by quartje** [comment]
That's already in the image: https://github.com/OpenConext/Stepup-Middleware/blob/develop/docker/Dockerfile.prod

This is caused by the manual cache clear that is run when setting up the environment. I've added it to the README.md
